### ISSUE TITLE
Missing thumbnails in merged mode

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#1039]
#  IMPORTANT BUG!

In last version I very often see a problem with randomly missing images in results grid.

- With every repeating search missing images are different. 
- This empty space is not clickable. 
- Please pay attention to the images results counter. It shows real number of the images, but some results are missed for some reason.
- Moreover, if you open neighbor to the missing image image in preview window and then go to the missing image in preview window, it will be correctly loaded. In preview window you can see all result including all images, missing in the results grid. 
- Looks like it some king of GUI problem with results grid. 

## First page loaded
only 9 of 22 images shown

![2017-08-22_094416 win7 mastercore](https://user-images.githubusercontent.com/22294259/29624945-11bec2be-8833-11e7-855d-91824cd8b2c3.png)

## Second page loaded
only 20 of 44 images shown
after loading second page images grid remakes and
now missing images are different compare with the previous screenshot, even on the first page part of the grid! Some missing images are shown now, and some shown images are missing now...  

![2017-08-22_095315 win7 mastercore](https://user-images.githubusercontent.com/22294259/29624956-16fa8cd6-8833-11e7-9213-5db3185f01ee.png)

## Second page loaded (another trying from different tab)
only 31 of 44 images shown
Another trying shows that same actions leads to different results, another images are missing from first try.  

![2017-08-22_125440 win7 mastercore](https://user-images.githubusercontent.com/22294259/29625012-3c707264-8833-11e7-9271-4f16823be941.png)

## Third page loaded
only 23 of 47 images shown
after loading third page images grid remakes again here is the result

![2017-08-22_095555 win7 mastercore](https://user-images.githubusercontent.com/22294259/29624963-1ade3d3e-8833-11e7-933d-1a6d7dc08396.png)

### How often does this problem occur? On which sources?
Randomly but very often, only in 5.5.0 (in previous versions all work fine).

Used merged results + endless page mode, all sources settings are default

![image](https://user-images.githubusercontent.com/22294259/29625481-81cf500e-8834-11e7-865b-a490c9de7230.png)

**Comment by Bionus** [comment]
Is there anything showing up in the log when this happens?
Do you have any blacklist set that might cause this?

**Comment by MasterPetrik** [comment]
> Do you have any blacklist set that might cause this?
No. And how can you explain why missing images are always different? That's obviously not connected to it. 

And I checked, shown and missing images in results in the grid can be from same source, so I guess this is not on server side, considering that in preview all images(even missing in grid) are shown correctly

> Is there anything showing up in the log when this happens?

Just tried another search, loaded first page:

![image](https://user-images.githubusercontent.com/22294259/29627623-4ebefe7e-883b-11e7-8cfe-9e2c36c26a90.png)

and here is the log text for that page 

[log text.txt](https://github.com/Bionus/imgbrd-grabber/files/1246229/log.text.txt)

**Comment by Bionus** [comment]
Can't reproduce unfortunately. :cry:

Do the missing images change if you resize the window around?

> and here is the log text for that page
> log text.txt
> for my view, nothing special in log found

Indeed, nothing to see there.

**Comment by Bionus** [comment]
Ok my bad I can reproduce.
It seems to only happen when using yande.re's big thumbnails.

**Comment by BarryMode** [comment]
I thought I would really like the grid view, but due to my slow internet, the loading was also slow so I found I liked the paginated view better.

**Comment by Bionus** [comment]
Yes, the current implementation of the fixed-width grid layout has some weird behaviors.

That's because I had to re-implement the whole layout system manually: Qt does not provide built-in this kind of layout. It only provides some basic layouts (horizontal, vertical, grid, etc.).

Also, some problems you mention don't come from the layout itself.  Overlaying images and wrong images order in grid for example are not related. What's related is the missing images (maybe), issue #955, or the weird flashy stuff (redraws, etc.) occurring when adding new images.

I'll see if some improvements can be done on this end. Another option would be to use the "official" [flow layout](https://doc.qt.io/qt-5/qtwidgets-layouts-flowlayout-example.html), which while not integrated in Qt, still is supported by them. The problem with this layout is the alignment of the items: They're all sticked together, and if there is too much space, you'll get a margin on the right side:

![flowlayout-example](https://user-images.githubusercontent.com/882719/29684927-031cd688-8914-11e7-8702-04aa275a1a06.png)

One could split this margin between the left and right side (by "centering" the whole layout), but the current Grabber layout splits it between every images, which is better in my opinion.

**Comment by Bionus** [comment]
> I thought I would really like the grid view, but due to my slow internet, the loading was also slow so I found I liked the paginated view better. In my short time using it, however, I didn't see any problems (probably because I only use one or two sources).

You mean the fixed-width grid layout? Why would your slow internet make it more ugly/slow? The only difference is the number of images per line: the old layout uses `sqrt(images.count())` while the new one somehow uses `window width / 150`.

**Comment by Bionus** [comment]
Well I went "screw it" and re-coded it all.
The layout should be smooth now, while keeping all its alignment stuff. Maybe it will fix #955 too (not sure).

**Comment by BarryMode** [comment]
@bionus, after reading what you said, I think my slow internet hunch is false. I was referring to the redraw lag stuff which sounds like it was just the way it was. I wish I knew QT, so I could contribute to stuff like this, as I hate seeing so many people report stuff but not really contributing actual code. Seems like it would be annoying to you.

**Comment by Bionus** [comment]
> after reading what you said, I think my slow internet hunch is false. I was referring to the redraw lag stuff which sounds like it was just the way it was

So this should hopefully be fixed in the next release (or in the `develop` branch thanks to commit 95714753b55ba482bf57db0300f56ffcc19209fa. Those on Windows who want to try it out and confirm it's indeed behaving better can find it in the [nightly version](https://github.com/Bionus/imgbrd-grabber/releases/tag/nightly).

> I wish I knew QT, so I could contribute to stuff like this, as I hate seeing so many people report stuff but not really contributing actual code. Seems like it would be annoying to you.

Yeah, I also wish more people contributed with code, but I can't really expect all the users to be able to contribute to the project, especially since it's not that easy to bootstrap and get into (even though this was greatly improved recently).

Those giving suggestions, finding bugs and reporting them in a polite/clear manner are also being helpful by helping me fix the bugs more easily.

And when I feel overwhelmed by the number of issues, I just take a break from the project and come back when I'm itching to code something. But to be honest, recently, more and more tickets are for suggestions, or small, "easy to fix" bugs, which is quite nice too.

**Comment by BarryMode** [comment]
@Bionus I'm excited to check out the grid!

**Comment by BarryMode** [comment]
Looks good to me, but if 
<img width="140" alt="screen shot 2017-08-25 at 4 32 09 pm" src="https://user-images.githubusercontent.com/5648875/29733500-fec3f9f0-89b2-11e7-8d1f-a6192ab8fbb0.png">
is turned off, it starts stacking the images. In infinite scrolling, it seems to load and stack indefinitely (if the above check box is not checked). Really nice though if scrolling is enabled! I like it.

**Comment by MasterPetrik** [comment]
> Also, some problems you mention don't come from the layout itself. Overlaying images and wrong images order in grid for example are not related. What's related is the missing images (maybe), issue #955, or the weird flashy stuff (redraws, etc.) occurring when adding new images.

I don't mean that they are related. But all these problems are result of some problems with grid filling, right? 

> That's because I had to re-implement the whole layout system manually

> the current Grabber layout splits it between every images, which is better in my opinion.

Indeed. And implementation is good enough. Better enchance it than use "official" flow layout.
I'm sorry for my words that overestimated some problems,   

> Well I went "screw it" and re-coded it all.
> The layout should be smooth now, while keeping all its alignment stuff. Maybe it will fix #955 too (not sure).

#955 looks fixed indeed, but do not rush and close that issue for now. I will make some checks in the nearest future to be sure.

**Comment by MasterPetrik** [comment]
> Those on Windows who want to try it out and confirm it's indeed behaving better can find it in the nightly version (there's an issue I'm aware of where the scroll area gets a big useless white space at the bottom).

I'm using last nightly version and can report that new grid system doesn't fixed problem with missing images because of yande.re. They are still missing in randow amount each reload of results.



### First try of search, only 2\21 images shown:

![2017-09-03_235058 win7 mastercore](https://user-images.githubusercontent.com/22294259/30008158-23eca10e-9125-11e7-9a9a-dbd1632ad0fc.png)

### Third retry of search, 20\21 images shown(image which missing in the grid is opened in preview window):

![2017-09-03_235212 win7 mastercore](https://user-images.githubusercontent.com/22294259/30008168-4cbad4f2-9125-11e7-9515-56b2e3078d3b.png)

### After ~5 rerty of search in same tab you finally can see all results in the grid:

![image](https://user-images.githubusercontent.com/22294259/30008257-3ab85ada-9126-11e7-9417-b8569295ba2a.png)

Also you can see a strange behavior of grabber with results for this request "kuze_matsuri" .
Thile there are only 21 original images, and all of them from page 1 from each source. But grabber says that there are also page 2 of resuts (you can see "more results" button on the screenshot above)
But when you press it, nothing will change, same number of results! Not a singe new image! 

![2017-09-04_040627 win7 mastercore](https://user-images.githubusercontent.com/22294259/30008280-87f7234e-9126-11e7-958c-9d6412643dcf.png)

Moreover, if you just go to page 2 by ">" button then you will see that there is 0 images on the page 2! but page 2 is exist anyway! Something looks not right, maybe bug?

![image](https://user-images.githubusercontent.com/22294259/30008357-98878ffe-9127-11e7-9414-e56970ae048a.png)

If you wanna try to reproduce it, here is my sources(https on gelbooru is enabled)
:
![image](https://user-images.githubusercontent.com/22294259/30008301-cf7c2ae8-9126-11e7-86cb-e18bc47667e1.png)


But now at least there are no more holes in new grid from missing images. (maybe overlaying images and other displacement issues now fixed too, who knows) Anyway that's a big step in improving grid system, so keep it up, you are on the right way!

P.C.
And please fix big useless white space at the bottom if you can, it's not very comfort to use grabber with it( 

Good luck!

**Comment by Bionus** [comment]
> I'm using last nightly version and can report that new grid system doesn't fixed problem with missing images because of yande.re. They are still missing in randow amount each reload of results.

That's actually a whole new problem with the merged results.
I'll work on it, thanks for letting me know.

> Also you can see a strange behavior of grabber with results for this request "kuze_matsuri" .
Thile there are only 21 original images, and all of them from page 1 from each source. But grabber says that there are also page 2 of resuts (you can see "more results" button on the screenshot above)
But when you press it, nothing will change, same number of results! Not a singe new image!
>
> Moreover, if you just go to page 2 by ">" button then you will see that there is 0 images on the page 2! but page 2 is exist anyway! Something looks not right, maybe bug?

I can't really reproduce this issue currently. Maybe the image setup changed? (the second page actually contains images for me)

But this can happen if for example all images on page 2 are already present on page 1 from other sources. The fact that manually loading the second page doesn't show anything is weird however.

> And please fix big useless white space at the bottom if you can, it's not very comfort to use grabber with it

Yes it's planned before the official release. 😉

**Comment by Bionus** [comment]
Ok actually the issue has never been related to yande.re. It was merely a coincidence.

The root cause was the modification done to implement #1025: when replacing an image with the new one with better tags, if the thumbnail of the first image hadn't loaded yet, it will be "lost", causing the blank spaces.

The fix should be included in the latest nightly. :+1:

**Comment by MasterPetrik** [comment]
> The fix should be included in the latest nightly.

Tested new Nightly a lot. Here is my report:
Indeed, now problem with missing thumblails is solved for 98% cases. 
Only one search request is still causing missing of the only one same thumbnail for some reason. 
All other tested requests with different parameters showed fully correct grid with right number of items even for several endless-scroll-pages. So it's a great sucsess. Thanks for actualy rework of grid filling system, now the new one is much stable compare to old one. Also I don't faced with old bugs with grid in new grid yet, so I can guess that they won't appear in new grid(But it's still too early for closing them, need more usage for clear result). Also I don't see a new bugs/problems in new nightly, so I think, it's almost ready to release.

Also problem with increases blank spaces in endless-page mode was fixed, thanks.

But the problem with blank space at the bottom of every results grid(even empty) in all (merged\unmerged) (paging\scrolling) modes is still relevant:
 
![2017-09-09_021922 win7 mastercoret](https://user-images.githubusercontent.com/22294259/30246125-a8358498-95f9-11e7-8faa-bc9704ea8774.png)

![image](https://user-images.githubusercontent.com/22294259/30246156-65b3acca-95fa-11e7-89bf-53439b77a253.png)

Hope you will fix it too.


And one more thing about new grid filling system. 

![image](https://user-images.githubusercontent.com/22294259/30246175-e0524054-95fa-11e7-97fe-b0fa02c92e25.png)


In old system, at first was shown correct total number of images results, and after that grid filling started.
In new system, I noticed, that at first grid filling starts, and only after that total number of images increases to correct number after a some seconds delay. Is that OK? Because now, for example, I can see 67 images, but total images number will be still 23 and only after some seconds it will show 67.

Anyway good job, looks like the main problem is solved and only few minor problems remains.

**Comment by Bionus** [comment]
> Only one search request is still causing missing of the only one same thumbnail for some reason.

Which one?

> Also I don't faced with old bugs with grid in new grid yet, so I can guess that they won't appear in new grid(But it's still too early for closing them, need more usage for clear result).

If you still don't see anything (I didn't meet any bug with it until now), feel free to close them whenever.

> Also I don't see a new bugs/problems in new nightly, so I think, it's almost ready to release.

Well I pushed a lot of changes in the past few days, especially regarding the HTML APIs, so that might not be true anymore. :sweat:
I'm planning a release this weekend though.

> But the problem with blank space at the bottom of every results grid(even empty) in all (merged\unmerged) (paging\scrolling) modes is still relevant:
>
> Hope you will fix it too.

> In old system, at first was shown correct total number of images results, and after that grid filling started.
> In new system, I noticed, that at first grid filling starts, and only after that total number of images increases to correct number after a some seconds delay. Is that OK? Because now, for example, I can see 67 images, but total images number will be still 23 and only after some seconds it will show 67.

I just pushed a fix for those, it should have reached nightly. :+1:

**Comment by MasterPetrik** [comment]
> Well I pushed a lot of changes in the past few days, especially regarding the HTML APIs, so that might not be true anymore. 

For testing those changes, just using nightly Grabber is enough? or I need to download some other files from develop branch?

> I'm planning a release this weekend though.

 Hmm, maybe it's not to late to make a couple suggestions before release :thinking: 

> I just pushed a fix for those, it should have reached nightly. 

Can confirm fixing those bugs, grid works very good and with no problems now.

> > Only one search request is still causing missing of the only one same thumbnail for some reason.
> 
> Which one?

Also, it's still relevant in the last nightly version too.

## Search with "kuze_matsuri" request

But to reproduce it you should use the same source set(as it set on the screenshot)
As you can see, only 20 from 21 images are shown(two pages loaded in scroll mode), repeating search alvays gives the same result. As you can see, image(opened in preview) is missing only in grid, but can be viewed in preview normally from the results list. That's strange.

![2017-09-21_084424 win7 mastercore](https://user-images.githubusercontent.com/22294259/30680582-1bdc6d96-9ea9-11e7-8a0d-7fbd5c03a86a.png)

Even more stange, that if you will use non merged mode, then you will see this image in grids from many sources, but if you change mode to merged, THIS image misses!

![2017-09-21_083425 win7 mastercore](https://user-images.githubusercontent.com/22294259/30680633-7a516886-9ea9-11e7-8094-c17bbc3e7521.png)

**Comment by Bionus** [comment]
> For testing those changes, just using nightly Grabber is enough? or I need to download some other files from develop branch?

You'll have to update your `model.xml` files from the `sites` folder:
https://github.com/Bionus/imgbrd-grabber/tree/develop/release/sites

Most have been updated with the new regular expressions, and new tag APIs (but those are not 100% tested yet).

> Hmm, maybe it's not to late to make a couple suggestions before release 🤔

Well there's still 3~4 days left after all.

> Can confirm fixing those bugs, grid works very good and with no problems now.

🎉 

> Search with "kuze_matsuri" request

Still can't reproduce, weird:
![image](https://user-images.githubusercontent.com/882719/30698297-cc8cd292-9ee1-11e7-900c-f40fee180a36.png)

Can you share the log with the "-d" flag passed to Grabber in the latest nightly? (using a shortcut with the path `"c:\path\to\Grabber.exe" -d` should do the trick and show some more lines in the log)

Also, I see in your screenshots that even though you have sankaku and danbooru selected, they yield no results, maybe that might be linked? (mine give results) Do you have the list of your selected sources, excluding those who don't give any results?

**Comment by MasterPetrik** [comment]
Used sites pressets from develope branch

Searched with this set of sources(it's important):
![image](https://user-images.githubusercontent.com/22294259/30743516-a4381322-9fa6-11e7-8ef0-fe4173320939.png)

Got different results in different tries with same settings:
## Bad try
![2017-09-22_041337 win7 mastercore](https://user-images.githubusercontent.com/22294259/30743395-0bd3c522-9fa6-11e7-8176-a658d3d2bf89.png)
[log bad.txt](https://github.com/Bionus/imgbrd-grabber/files/1324409/log.bad.txt)
## Good try
![2017-09-22_041345 win7 mastercore](https://user-images.githubusercontent.com/22294259/30743384-03799fdc-9fa6-11e7-8c0f-b25a09b28d98.png)
[log good.txt](https://github.com/Bionus/imgbrd-grabber/files/1324406/log.good.txt)

**Comment by MasterPetrik** [comment]
After replacing all my sources with develop branch sources...
Why now all my my sources icons looks like this?
![2017-09-22_150400 win7 mastercore](https://user-images.githubusercontent.com/22294259/30743699-786e8ce8-9fa7-11e7-8661-c1b0cf6466e4.png)
It tells that some update is aviable but I can't see where I can update them :thinking: 

Also, let's count it as GUI bug: sources window have constant heigth, and with not many sources it's too much blank space in it/ Resizing the window doesn't saves(

**Comment by MasterPetrik** [comment]
Looks like the fix doesn't fixed it after all

![image](https://user-images.githubusercontent.com/22294259/30776494-07ccf934-a0b0-11e7-91d9-5e3559ea06cc.png)

**Comment by Bionus** [comment]
I could reproduce indeed, it comes from a corrupted file from Safebooru:
http://safebooru.org/thumbnails/1274/thumbnail_3da04833a454153e885384bfb9886dda681773a4.jpg

Given this kind of issue is not widespread, very specific etc, from now on Grabber will show a placeholder images for failed thumbnail loads (it won't try other sources in merged mode, the cost/gain is too high).

**Comment by MasterPetrik** [comment]
> Given this kind of issue is not widespread, very specific etc, from now on Grabber will show a placeholder images for failed thumbnail loads (it won't try other sources in merged mode, the cost/gain is too high).

Congatulations with succesful investigation! Indeed, now it's works correct. 
Now If thumbnail is broken, you resize original image and make thimbnail from it, am I right?

**Comment by MasterPetrik** [comment]
Also I found another strange behavior, if you mind to investigate it too...:smirk:

Same sources set. Last nightly.
##  "8c" search request 
![2017-09-24_151422 win7 mastercore](https://user-images.githubusercontent.com/22294259/30782475-9e9ed586-a13b-11e7-9620-c40772a0e751.png)
![2017-09-24_151435 win7 mastercore](https://user-images.githubusercontent.com/22294259/30782477-a2513052-a13b-11e7-9ba6-9fa9cd293509.png)

For some reason I don't have a "load more results" button(endless page button mode enabled)at the bottom of the window in both merged and non merged modes, also I can go to the next results page via ">" button, and it will work fine, but it's very-very strange, for other search requests all work fine.

**Comment by MasterPetrik** [comment]
also sometimes many images in results grid are not clickable, I don't know the reason, but it happens only in new grid system

**Comment by Bionus** [comment]
Because of some other issue that I also fixed last hour.

**Comment by MasterPetrik** [comment]
Ok, all mantioned here issues indeed has beed fixed in 5.5.1. I suppose new issues with grid I will post in new issues, thanks
