### ISSUE TITLE
Add Right Click Menu Save Files In Download Queue

### ISSUE THREAD

**Issue by brazenvoid** [Bionus/imgbrd-grabber#1627]
**Is your feature request related to a problem? Please describe**

Currently if one closes the tab, the downloads get cancelled. There is also no confirmation dialog or any intimation that downloads are ongoing.

**Describe the solution you'd like**

Regardless of how downloads are added, they must be added to the download queue so they remain independent of the tab they were initiated on. Also the user will be able to see the progress on them as well. 

If they are through the download menu item, they will just start automatically.

**Comment by Bionus** [comment]
It's funny tyhat

**Comment by Bionus** [comment]
It's funny that you're posting those issues now since I've started working on this at the beginning of the week. So yes it's totally planned, as it's necessary for the rework of batch downloads I'm planning (necessary for concurrent batch downloads that do NOT take focus, kind of what you described in #1628). 😄

I just pushed a few modifications to add the queue for the right click and monitors (see #1620), it should land in nightly soon.

**Comment by brazenvoid** [comment]
I don't see any getting added in the downloads page at all. 

I always have internet issues for 2-3 hours a day where my VPN randomly fails thus resulting in failed downloads. Like currently it is failing on every 4th/5th image but I still don't get the option to retry them at all...

**Comment by Bionus** [comment]
> Currently if one closes the tab, the downloads get cancelled. There is also no confirmation dialog or any intimation that downloads are ongoing.

What was done is to make downloads independent from the tab you're on, so you can now close the tab and nothing will change.

There is no new part in the "Downloads" tab or anything. Because if you just want to add images to the downloads tab, you can already do so. Just use <kbd>Ctrl + Click</kbd> (or <kbd>Ctrl + Shift + Click</kbd> for range selection) and then click "Add selected". Selected images will be added to the Downloads tab where you can download them like any other download.

**Comment by brazenvoid** [comment]
I know what that feature is. But it is still more convenient to use the right click save option instead doing Ctrl+Click. At least the program will download simultaneously rather than afterwards the user has to initiate the download manually. For users like me who use VPN for these, its actually bad as we have to live with the VPN even afterwards and wait for the downloads to finish.

**Comment by brazenvoid** [comment]
I meant adding the downloads to downloads tab, inferred from download queue. I am a user, not the developer of the program. I don't know what you make or name inside it.
