### ISSUE TITLE
Bug: "save" function works very strange and some other problems with this function

### ISSUE THREAD

**Issue by MasterPetrik** [Bionus/imgbrd-grabber#926]
### 1. When you try to "save"image via rightclisk meny from results grid, in fact it not saves:

1. you click "save" on some image in results grid.
2. image is not saved.
3. you open this image in preview window
4. in this moment image saves in the folder
5. if you will not open it in preview window, image will not be saved

### 2. And another problem:
after you saves image via "save" in grid, when you open this image in preview window, there are will be button "save" instead of "delete" button, but if you will go to previous\next image and back or just reopen preview window for this image, button will became "delete".

### 3. And another problem:
after image is saved via "save" from results grid, while another opening of rightclick menu there are still will be "save" option, more logicaly switch it to "delete" option after saving
![image](https://cloud.githubusercontent.com/assets/22294259/26287155/f69c2642-3e7d-11e7-9362-4f06c62293a8.png)
### How often does this problem occur?
100% reprodusable

### What version of the program are you using? On what operating system?
5.3.2 win 7

### Please provide any additional information below
here is the video of the process
https://drive.google.com/open?id=0B3SK4Pf9wsnmZU42TmlvZklkMUE

**Comment by Bionus** [comment]
I could only reproduce in this situation:
1. Open the image in preview window
2. Close the preview window
3. Click "Save" in the results
4. Image is not saved
5. Open preview window
6. Image is saved

Steps 1 and 2 (opening the preview window first) were necessary to reproduce on my end.
I just pushed a fix for it.

**Comment by MasterPetrik** [comment]
> It's a side-effect of the same issue.

Indeed, that's why I posted it in this topic.

> I just pushed a fix for it.

Well, lets see will it completely fix it. If not, I will tell you) 

BTW, can you update translation files before you relese 5.3.3? maybe I can make a translation update before patch.

**Comment by Bionus** [comment]
> BTW, can you update translation files before you relese 5.3.3? maybe I can make a translation update before patch.

Here you go. 👍
Make sure to check in the `develop` branch.

**Comment by MasterPetrik** [comment]
is it OK?
![image](https://cloud.githubusercontent.com/assets/22294259/26380151/8324df34-4025-11e7-9dba-6845ab217525.png)

**Comment by MasterPetrik** [comment]
@Bionus need to reopen, by many reasons.

> I could only reproduce in this situation:
> 
> Open the image in preview window
> Close the preview window
> Click "Save" in the results
> Image is not saved
> Open preview window
> Image is saved

This way still reproduse the bug. Nothing changed with it.

in fact, ALL this issue was undone:
first problem isn't fixed
second problem depends of first, so it isn't fixes too.
third problem even wasn't tried to be fixed(
and even russian translation isn't updated in 5.3.3. I don't know why .ts file in your repo is OK but  5.3.3 installer installs old RU version, can you check this too?

**Comment by MasterPetrik** [comment]
BTW, I have a little suggestion about icons in this menu.
current hash icon is:
1. too big
2. too bold
3. too black

all other icons in this menu are in blue colors so this is a big contrast. And I'm just a bit changed your hash icon to make it more suitable:
![sgs](https://cloud.githubusercontent.com/assets/22294259/26475146/637f615a-41be-11e7-8e94-9814cb7b4373.png)

current icon:
![hash](https://cloud.githubusercontent.com/assets/22294259/26475231/0bba7e90-41bf-11e7-9af0-5fd4206bc618.png)
new icon:
![has h](https://cloud.githubusercontent.com/assets/22294259/26475236/19dcb79a-41bf-11e7-9c93-749bf3fe0e31.png)

I think the new one it's a much better, hehe)
Feel free to use it if you like.

BTW, to determine, does RU version updated you can just switch language to RU and see at this right click menu: If it's in english then it's still an old translation.

**Comment by brodycas3** [comment]
Thats a good change to work better with the dark theme/'

**Comment by Bionus** [comment]
Indeed, that icon is better.
I actually initially just used the first result for "hash icon" on Google images. 😛 

> BTW, to determine, does RU version updated you can just switch language to RU and see at this right click menu: If it's in english then it's still an old translation.

![image](https://cloud.githubusercontent.com/assets/882719/26475402/022adc00-41b8-11e7-89fa-2d5b3073ab22.png)

**Comment by MasterPetrik** [comment]
well, if it work for you then ok. 
Anyway I can compile .qm file for me manually from .ts source. QT linguist indeed a great tool) 

P.S. I see a great Great enthusiasm in you about Grabber in last two days, it makes me happy. Who knows, maybe you even add the most expected function for me in 5.4.0 with this energie, who knows...

**Comment by Bionus** [comment]
> P.S. I see a great Great enthusiasm in you about Grabber in last two days, it makes me happy.

Because I have lots of free time :smile:

> Who knows, maybe you even add the most expected function for me(#886) in 5.4.0 with this energy, who knows...

😋

**Comment by MasterPetrik** [comment]
I guess minus sign is a wrong icon, minus means removeing from something(after adding)
and cross means deleting (after saving), it's more logical.
![2017-06-17_211009 win7 mastercore](https://user-images.githubusercontent.com/22294259/27255230-b27e43ac-53a2-11e7-9305-5c9728b16347.png)

all other about this issue work well now, thx
